### ISSUE TITLE
battery life time

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#55]
Not systematically measured, I had overnight battery level drop from 89% to 60%, on stock OEM ROM the drop was below 5% as far as I remember. I will add new measurements over the next days.

**Comment by rinigus** [comment]
Its related to #27 

Checked today and on 3.2.1.20

State right now: 

- flight mode is fine, suspend times are exactly as they should be. 
- without network but calls allowed, during night, I've got discharge for about 4% with sleep times on average ~12s (from 10-30s typical, max 70s). 
- with network (cellular) and sometimes use (day), we are talking about 7s suspend times (below 15s all). 

I do wonder whether AOSP has longer suspend times with SIM card active and network used.

**Comment by pagism** [comment]
not sure about suspend time, I guess you're referring to mobile network connection, in my case I had no sim card in, only wifi.

**Comment by rinigus** [comment]
WiFi is difficult to debug, usually its worse than on cellular data.

Was stock with WIFI as well? Do you have some network accounts configured? Are they pulling with some time interval or set to 'always on'? Were the account settings the same for AOSP and SFOS?

Realistically, we can work on getting parity without network. With network, you get too many variables and SFOS doesn't have push data support from Google servers, as Android has. Assuming that you used Android with Google apps installed

**Comment by pagism** [comment]
Same conditions, Android had a basic google account no other installations, wifi was on, no sim card. On SFOS X I had a "mixed" upgrade to 3.2.1.20, wifi on, jolla account enabled, weather app, and telegrame which was not running. I had also installed collectd/RRDtool but I could not make it running, so it might had be running in background? I've removed them now.
I need to be more systematic tho, I will try to measure things with both wifi/wlan off, just the SFOS idling.

**Comment by rinigus** [comment]
Do you have any email/calendar accounts enabled?

Let's see if you have anomalies without WIFI or other connections. That's something which should be easy to check.

As for collectd/rrdtool: you have to install https://openrepos.net/content/rinigus/systemdatascope and go through its config (see very short version and just follow that in its start screen). Without that config, it will not run by itself. I, obviously, use that for monitoring the system and that's why I could pull out the stats. Quite handy for such debugging

**Comment by pagism** [comment]
no email/calendar accounts enabled yet, developer mode is on, but I will turn off ssh and lets see what we get.

I am a bit suspicious of system monitoring tools overhead, we can start with an empty system, then I can add monitoring tools and find their overhead, then services.

**Comment by rinigus** [comment]
@pagism: sure, you could start without system monitoring. collectd is rather gentle usually, unless system config is wrong (as it was before I updated it to take into account differences in storage of XZ2 when compared to older models).

My data is acquired with collectd running on each boot

**Comment by rinigus** [comment]
To get some stats, unless you want to use collectd, you could use the following:

Recordings have to be done before and after the interval. These are:

```
cat /sys/kernel/debug/suspend_stats
mcetool --get-suspend-stats
```

The first one will give you number of suspend attempts: success and fail. The second one will tell you how much uptime (wall clock) and out of it time in suspend. We will need increase in suspend_time divided by increase in success. That way you can get average time of a single suspend. 

Try to find that out together with battery % drop per hour with and without WIFI.

**Comment by pagism** [comment]
46% in 4hours (64-18), wifi off, no sim, it's too high by any means. Unless i did something  horribly wrong.

Anyway, i need to be more systematic, it's  charging now, i will use the stats you suggested tomorrow.

**Comment by rinigus** [comment]
This is VERY bad. Sometimes, trackers go on after updates, but probably you don't have too many files over there.

Check if you get suspended at all (mcetools) and which processes are high in top. Try to reboot as well. Without network, I have very low consumption, as described above.

**Comment by pagism** [comment]
no chance to get stats overnight, battery depleted from 55% to ~0 in 4h 41m, no low battery sound notification either (unless i missed it)

**Comment by pagism** [comment]
After some charging I managed to get some stats over a 2 hour period:
initial conditions, booting after charging, wifi off, no sim, no email or calendar accounts yet
initial charge 83% dropped to 79% after 1st hour, and after 2nd hour at 78%
```
success: 0
fail: 0
failed_freeze: 0
failed_prepare: 0
failed_suspend: 0
failed_suspend_late: 0
failed_suspend_noirq: 0
failed_resume: 0
failed_resume_early: 0
failed_resume_noirq: 0
failures:
  last_failed_dev:	
			
  last_failed_errno:	0
			0
  last_failed_step:	
			
uptime:       276.904 
suspend_time: 0.000 
[nemo@Sailfish ~]$ more 2.log
success: 77
fail: 9
failed_freeze: 9
failed_prepare: 0
failed_suspend: 0
failed_suspend_late: 0
failed_suspend_noirq: 0
failed_resume: 0
failed_resume_early: 0
failed_resume_noirq: 0
failures:
  last_failed_dev:	
			
  last_failed_errno:	-16
			-16
  last_failed_step:	freeze
			freeze
uptime:       3832.032 
suspend_time: 3210.793 
[nemo@Sailfish ~]$ more 3.log 
success: 99
fail: 11
failed_freeze: 11
failed_prepare: 0
failed_suspend: 0
failed_suspend_late: 0
failed_suspend_noirq: 0
failed_resume: 0
failed_resume_early: 0
failed_resume_noirq: 0
failures:
  last_failed_dev:	
			
  last_failed_errno:	-16
			-16
  last_failed_step:	freeze
			freeze
uptime:       7487.509 
suspend_time: 6697.179
```
